include:
  - project: "GNOME/citemplates"
    file: "flatpak/flatpak_ci_initiative.yml"

stages:
  - lint
  - test
  - flatpak

lint-alpine:
  image: alpine:edge
  stage: lint
  before_script:
    - apk add build-base gtk4.0 libadwaita python3 py3-gobject3 py3-filetype py3-mutagen py3-pillow py3-aiohttp py3-aiohttp-retry py3-aiofiles py3-pyacoustid ffmpeg ruff
  script:
    - ruff check --select=E9,F63,F7,F82,F821 src tests
    - ruff format --check src tests
    - ruff check --exit-zero src tests
  allow_failure: true

.test-common:
  script:
    - meson setup _build -Denable_networked_tests=true
    - meson compile -C _build
    - meson test "eartag*:" -v -C _build
    - meson install -C _build

test-alpine:
  stage: test
  image: alpine:edge
  extends: .test-common
  before_script:
    - apk add build-base git gtk4.0-dev libadwaita-dev meson python3 py3-gobject3 py3-filetype py3-mutagen py3-pillow py3-aiohttp py3-aiohttp-retry py3-aiofiles py3-xxhash desktop-file-utils appstream-glib gettext py3-pytest py3-pytest-asyncio py3-flake8 py3-pyacoustid

.vars-devel:
  variables:
    MANIFEST_PATH: "build-aux/flatpak/app.drey.EarTag.Devel.json"
    FLATPAK_MODULE: "eartag"
    APP_ID: "app.drey.EarTag.Devel"
    RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
    BUNDLE: "app.drey.EarTag.Devel.flatpak"
    CONFIG_OPTS: "-Ddebug=true"
    RUN_TESTS: "0"

# Build Flatpak for x86_64
flatpak@x86_64:
  stage: flatpak
  extends: ['.flatpak@x86_64', '.vars-devel']

# Build Flatpak for aarch64
flatpak@aarch64:
  stage: flatpak
  extends: ['.flatpak@aarch64', '.vars-devel']

nightly@x86_64:
  stage: flatpak
  extends: '.publish_nightly'
  needs: ['flatpak@x86_64']

nightly@aarch64:
  stage: flatpak
  extends: '.publish_nightly'
  needs: ['flatpak@aarch64']
