include:
  - project: "GNOME/citemplates"
    file: "flatpak/flatpak_ci_initiative.yml"

.vars-devel:
  variables:
    MANIFEST_PATH: "build-aux/flatpak/app.drey.EarTag.Devel.json"
    FLATPAK_MODULE: "eartag"
    APP_ID: "app.drey.EarTag.Devel"
    RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
    BUNDLE: "app.drey.EarTag.Devel.flatpak"
    CONFIG_OPTS: "-Ddebug=true"
    RUN_TESTS: "0"
    PULL_CACHE: "0"

# Build Flatpak for x86_64
flatpak@x86_64:
  extends: ['.flatpak@x86_64', '.vars-devel']

# Build Flatpak for aarch64
flatpak@aarch64:
  extends: ['.flatpak@aarch64', '.vars-devel']

nightly@x86_64:
  extends: '.publish_nightly'
  needs: ['flatpak@x86_64']

nightly@aarch64:
  extends: '.publish_nightly'
  needs: ['flatpak@aarch64']
